name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t backend-image ./backend

      - name: Build frontend Docker image
        run: docker build -t frontend-image ./frontend
